# Generated by Django 4.2.7 on 2023-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_slugifymodelmixins_alter_laptop_prise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlugifyModelMixins',
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='ozu',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='ssd',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
