# Generated by Django 4.2.7 on 2023-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_delete_slugifymodelmixins_laptop_cpu_laptop_ozu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, default='img/lenovo_legion_pro_5_Gen_8.jpg', null=True, upload_to='img'),
        ),
    ]
