# Generated by Django 4.2.7 on 2023-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_alter_laptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
